### ISSUE TITLE
Will the pre-trained model be released in the future?

### ISSUE THREAD

**Issue by PeeBar** [chowy333/WMKPN-Burst_Super-Resolution#1]
Hi! I can't find the file'./scripts/test_WMKPN.sh' in this repository. Will you release this file and your pre-trained models in the future?

**Comment by chowy333** [comment]
Hello, Xu.

Thank you for your interest in my research.

I'm planning to update all the files including model.py and pre-trained files until mid of this month.

Sincerely,
Wooyeong Cho

조우영&nbsp;CHO, WOOYEONG전기및전자공학부&nbsp;/&nbsp;석사34141 대전광역시 유성구 대학로 291 한국과학기술원(KAIST)Email&nbsp; ***@***.*** ***@***.***



-----Original Message-----
From: "XuJZ" ***@***.***&gt;
To: "chowy333/WMKPN-Burst_Super-Resolution" ***@***.***&gt;;
Cc: "Subscribed" ***@***.***&gt;;
Sent: 2021-11-04 (목) 11:02:02 (UTC+09:00)
Subject: [chowy333/WMKPN-Burst_Super-Resolution] Will you release your pre-trained models in the future? (Issue #1)


Hi! I can't find the file'./test_WMKPN.sh' in this repository. Will you release this file and your pre-trained models in the future?

**Comment by PeeBar** [comment]
Hi, Cho,

Thank you so much for your generous sharing! I am looking forward to your update!

Sincerely,
Xu

**Comment by chowy333** [comment]
Hello, Xu.

I'm writing this email for letting you know that my work, WMKPN, is going to be on patent, which my professor prevented me from opening the source code.

Fortunately, I could give you some hints related to our model if you have any further questions.&nbsp;

So, feel free to ask me what you have been curious about!

Sincerely,
Wooyeong Cho

조우영&nbsp;CHO, WOOYEONG전기및전자공학부&nbsp;/&nbsp;석사34141 대전광역시 유성구 대학로 291 한국과학기술원(KAIST)Email&nbsp; ***@***.*** ***@***.***



-----Original Message-----
